# Generated by Django 4.0.6 on 2022-08-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_user_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='openListing',
            field=models.BooleanField(default=False),
        ),
    ]
