# Generated by Django 4.0.6 on 2022-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_openlisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='openListing',
            field=models.BooleanField(default=True),
        ),
    ]
